/**********************************************************************
** Name            : ABIT_CARE_PROGRAM_DETAILS_REPORT.sql
**
** Description     : DDL for ABIT_CARE_PROGRAM_DETAILS_REPORT.
**                   CREATE-only script deployed via CI. Populated
**                   separately by PBI_XXXXXXX_Populate_ABIT_CARE_
**                   PROGRAM_DETAILS_REPORT.sql in 50_DbPostUpd —
**                   do not add INSERT/DML here, CI deploy will fail.
**                   Column order mirrors ABIT_CARE_PROGRAM_DETAILS_
**                   REPORT_RAW; column types reflect the target
**                   (post-split/post-cast) shape, not the raw shape.
**
** Developed By    : BI DW DEV
** Date Created    : 08/16/2026
**
** Change History  :
** Mod            Date         Name           Reason
**----------------------------------------------------------------
** PBI_XXXXXXX    08/16/2026   Abhi M         Initial
**
**------------------------------------------------------------------
**********************************************************************/

--  OBJECT ABIT_CARE_PROGRAM_DETAILS_REPORT
USE SCHEMA ADMIN;

CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ABIT_CARE_PROGRAM_DETAILS_REPORT');

CREATE OR REPLACE TABLE ABIT_CARE_PROGRAM_DETAILS_REPORT (
    CLIENT VARCHAR(16777216),
    LOB VARCHAR(16777216),
    PLAN_TYPE VARCHAR(16777216),
    OPS_SEGMENT VARCHAR(16777216),
    TPA_NAME VARCHAR(16777216),
    PATIENT VARCHAR(16777216),
    DATE_OF_BIRTH TIMESTAMP_NTZ,
    PATIENT_ID NUMBER(38,0),
    PROGRAM VARCHAR(16777216),
    PROGRAM_ID VARCHAR(16777216),
    PCP_CARE_COORDINATION_NAME VARCHAR(16777216),
    PCP_CARE_COORDINATION_NPI VARCHAR(16777216),
    PCP_INSURANCE_NAME VARCHAR(16777216),
    PCP_INSURANCE_NPI VARCHAR(16777216),
    PRACTICE_NAME VARCHAR(16777216),
    PROVIDER_OUTREACH_REQUESTED VARCHAR(10),
    PROGRAM_STATUS VARCHAR(16777216),
    PROGRAM_PRIORITY VARCHAR(16777216),
    REFERRAL_SOURCE VARCHAR(16777216),
    DELIVERY_MODEL VARCHAR(16777216),
    REASON_FOR_PROGRAM VARCHAR(16777216),
    PRIMARY_STAFF_MEMBER VARCHAR(16777216),
    PRIMARY_STAFF_ROLE VARCHAR(16777216),
    OTHER_CARE_TEAM_MEMBER VARCHAR(16777216),
    OTHER_CARE_TEAM_MEMBER_ROLE VARCHAR(16777216),
    DATE_PRIMARY_STAFF_ASSIGNED TIMESTAMP_NTZ,
    FACILITY_NAME VARCHAR(16777216),
    FACILITY_TYPE VARCHAR(16777216),
    ADMIT_DATE TIMESTAMP_NTZ,
    TARGET_DISCHARGE_DATE TIMESTAMP_NTZ,
    ACTUAL_DISCHARGE_DATE TIMESTAMP_NTZ,
    DISCHARGE_DISPOSITION VARCHAR(16777216),
    DISCHARGE_DELAY_REASON VARCHAR(16777216),
    PROGRAM_CREATE_DATE TIMESTAMP_NTZ,
    PROGRAM_CREATED_BY VARCHAR(16777216),
    PROGRAM_ASSIGNED_DATE TIMESTAMP_NTZ,
    PROGRAM_START_DATE TIMESTAMP_NTZ,
    PROGRAM_CLOSED_DATE TIMESTAMP_NTZ,
    LAST_PROGRAM_ACTIVITY_DATE TIMESTAMP_NTZ,
    LAST_PROGRAM_ACTIVITY_BY VARCHAR(16777216),
    TOTAL_SUBMITTED_ASSESSMENTS NUMBER(38,0),
    TOTAL_DRAFT_ASSESSMENTS NUMBER(38,0),
    FIRST_ASSESSMENT_SUBMITTED_DATE_ENGAGEMENT_DATE TIMESTAMP_NTZ,
    LAST_ASSESSMENT_SUBMITTED_DATE TIMESTAMP_NTZ,
    NAME_OF_LAST_SUBMITTED_ASSESSMENT VARCHAR(16777216),
    ENGAGED_DATE TIMESTAMP_NTZ,
    TOTAL_PATIENT_CONTACTS NUMBER(38,0),
    FIRST_PATIENT_CONTACT_DATE TIMESTAMP_NTZ,
    LAST_PATIENT_CONTACT_DATE TIMESTAMP_NTZ,
    TOTAL_UNSIGNED_CARE_NOTES NUMBER(38,0),
    TOTAL_OPEN_ACTION_ITEMS NUMBER(38,0),
    TOTAL_OVERDUE_ACTION_ITEMS NUMBER(38,0),
    TOTAL_SUCCESSFULLY_CLOSED_PROGRAM_GRADUATION_GOALS NUMBER(38,0),
    TOTAL_OVERDUE_GOALS NUMBER(38,0),
    TOTAL_OVERDUE_INTERVENTIONS NUMBER(38,0),
    FIRST_CARE_PLAN_DATE TIMESTAMP_NTZ,
    NUMBER_OF_CARE_PLANS NUMBER(38,0),
    LAST_PCSP_COMPLETED VARCHAR(16777216),
    TOTAL_PCSPS_COMPLETED VARCHAR(16777216),
    LAST_CMR_SUBMITTED_DATE TIMESTAMP_NTZ,
    WELCOME_PACKET_GENERATED_DATE TIMESTAMP_NTZ,
    TOTAL_LETTERS_GENERATED NUMBER(38,0),
    TOTAL_UPLOADED_DOCUMENTS VARCHAR(16777216),
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ABIT_CARE_PROGRAM_DETAILS_REPORT TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ABIT_CARE_PROGRAM_DETAILS_REPORT TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ABIT_CARE_PROGRAM_DETAILS_REPORT TO ROLE XXX_OWNER COPY CURRENT GRANTS');