/**********************************************************************
** Name            : ABIV_CARE_PROGRAM_DETAILS_REPORT.sql
**
** Description     : DDL
**
** Developed By    : BI DW DEV
** Date Created    : 08/17/2026
**
** Change History  :
** Mod            Date         Name           Reason
**----------------------------------------------------------------
** PBI_XXXXXXX    08/17/2026   Abhi M         Initial
**
**------------------------------------------------------------------
**********************************************************************/

--  OBJECT ABIV_CARE_PROGRAM_DETAILS_REPORT
USE SCHEMA ADMIN;

CALL TOOLS.ADMIN.SP_DROP_OBJECT ('VIEW', 'ADMIN.ABIV_CARE_PROGRAM_DETAILS_REPORT');

CREATE VIEW ABIV_CARE_PROGRAM_DETAILS_REPORT
( CLIENT, LOB, PLAN_TYPE, OPS_SEGMENT, TPA_NAME, PATIENT, DATE_OF_BIRTH, PATIENT_ID, PROGRAM, PROGRAM_ID, PCP_CARE_COORDINATION_NAME, PCP_CARE_COORDINATION_NPI, PCP_INSURANCE_NAME, PCP_INSURANCE_NPI, PRACTICE_NAME, PROVIDER_OUTREACH_REQUESTED, PROGRAM_STATUS, PROGRAM_PRIORITY, REFERRAL_SOURCE, DELIVERY_MODEL, REASON_FOR_PROGRAM, PRIMARY_STAFF_MEMBER, PRIMARY_STAFF_ROLE, OTHER_CARE_TEAM_MEMBER, OTHER_CARE_TEAM_MEMBER_ROLE, DATE_PRIMARY_STAFF_ASSIGNED, FACILITY_NAME, FACILITY_TYPE, ADMIT_DATE, TARGET_DISCHARGE_DATE, ACTUAL_DISCHARGE_DATE, DISCHARGE_DISPOSITION, DISCHARGE_DELAY_REASON, PROGRAM_CREATE_DATE, PROGRAM_CREATED_BY, PROGRAM_ASSIGNED_DATE, PROGRAM_START_DATE, PROGRAM_CLOSED_DATE, LAST_PROGRAM_ACTIVITY_DATE, LAST_PROGRAM_ACTIVITY_BY, TOTAL_SUBMITTED_ASSESSMENTS, TOTAL_DRAFT_ASSESSMENTS, FIRST_ASSESSMENT_SUBMITTED_DATE_ENGAGEMENT_DATE, LAST_ASSESSMENT_SUBMITTED_DATE, NAME_OF_LAST_SUBMITTED_ASSESSMENT, ENGAGED_DATE, TOTAL_PATIENT_CONTACTS, FIRST_PATIENT_CONTACT_DATE, LAST_PATIENT_CONTACT_DATE, TOTAL_UNSIGNED_CARE_NOTES, TOTAL_OPEN_ACTION_ITEMS, TOTAL_OVERDUE_ACTION_ITEMS, TOTAL_SUCCESSFULLY_CLOSED_PROGRAM_GRADUATION_GOALS, TOTAL_OVERDUE_GOALS, TOTAL_OVERDUE_INTERVENTIONS, FIRST_CARE_PLAN_DATE, NUMBER_OF_CARE_PLANS, LAST_PCSP_COMPLETED, TOTAL_PCSPS_COMPLETED, LAST_CMR_SUBMITTED_DATE, WELCOME_PACKET_GENERATED_DATE, TOTAL_LETTERS_GENERATED, TOTAL_UPLOADED_DOCUMENTS, LOAD_TS )
AS
SELECT
    ABIT_CARE_PROGRAM_DETAILS_REPORT.CLIENT,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LOB,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PLAN_TYPE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.OPS_SEGMENT,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TPA_NAME,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PATIENT,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.DATE_OF_BIRTH,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PATIENT_ID,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_ID,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PCP_CARE_COORDINATION_NAME,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PCP_CARE_COORDINATION_NPI,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PCP_INSURANCE_NAME,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PCP_INSURANCE_NPI,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PRACTICE_NAME,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROVIDER_OUTREACH_REQUESTED,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_STATUS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_PRIORITY,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.REFERRAL_SOURCE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.DELIVERY_MODEL,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.REASON_FOR_PROGRAM,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PRIMARY_STAFF_MEMBER,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PRIMARY_STAFF_ROLE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.OTHER_CARE_TEAM_MEMBER,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.OTHER_CARE_TEAM_MEMBER_ROLE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.DATE_PRIMARY_STAFF_ASSIGNED,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.FACILITY_NAME,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.FACILITY_TYPE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.ADMIT_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TARGET_DISCHARGE_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.ACTUAL_DISCHARGE_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.DISCHARGE_DISPOSITION,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.DISCHARGE_DELAY_REASON,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_CREATE_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_CREATED_BY,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_ASSIGNED_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_START_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.PROGRAM_CLOSED_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LAST_PROGRAM_ACTIVITY_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LAST_PROGRAM_ACTIVITY_BY,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_SUBMITTED_ASSESSMENTS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_DRAFT_ASSESSMENTS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.FIRST_ASSESSMENT_SUBMITTED_DATE_ENGAGEMENT_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LAST_ASSESSMENT_SUBMITTED_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.NAME_OF_LAST_SUBMITTED_ASSESSMENT,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.ENGAGED_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_PATIENT_CONTACTS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.FIRST_PATIENT_CONTACT_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LAST_PATIENT_CONTACT_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_UNSIGNED_CARE_NOTES,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_OPEN_ACTION_ITEMS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_OVERDUE_ACTION_ITEMS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_SUCCESSFULLY_CLOSED_PROGRAM_GRADUATION_GOALS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_OVERDUE_GOALS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_OVERDUE_INTERVENTIONS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.FIRST_CARE_PLAN_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.NUMBER_OF_CARE_PLANS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LAST_PCSP_COMPLETED,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_PCSPS_COMPLETED,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LAST_CMR_SUBMITTED_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.WELCOME_PACKET_GENERATED_DATE,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_LETTERS_GENERATED,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.TOTAL_UPLOADED_DOCUMENTS,
    ABIT_CARE_PROGRAM_DETAILS_REPORT.LOAD_TS
FROM ADMIN.ABIT_CARE_PROGRAM_DETAILS_REPORT;

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON VIEW ADMIN.ABIV_CARE_PROGRAM_DETAILS_REPORT TO ROLE XXX_RESTRICTED_VIEWREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON VIEW ADMIN.ABIV_CARE_PROGRAM_DETAILS_REPORT TO ROLE XXX_OWNER COPY CURRENT GRANTS');