/**********************************************************************
** Name            : ASDT_WRAPUP_SUMMARY_FINAL_TABLES.sql
**
** Description     : DDL for the 5 wrapup_summary final tables.
**                   CONVERSATION (header) : INQUIRY (1-to-many, FK
**                   CONVERSATION_ID) : INQUIRY_INTENT /
**                   INQUIRY_KEY_POINT / INQUIRY_TOPIC (many-to-one,
**                   FK INQUIRY_ID). Tables are dropped child-to-parent
**                   and created parent-to-child so each FK always has
**                   a valid parent to reference at create time.
**                   NOTE: Snowflake PK/FK constraints are declarative
**                   only and are not enforced at runtime.
**
** Developed By    : BI DW DEV
** Date Created    : 08/16/2026
**
** Change History  :
** Mod            Date         Name           Reason
**----------------------------------------------------------------
** PBI_1830398    08/16/2026   Abhi M         Initial
**
**------------------------------------------------------------------
**********************************************************************/
USE SCHEMA ADMIN;

--==========================================================================
--Step 1: Drop existing final tables (child-to-parent order)
--==========================================================================

CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDT_WRAPUP_SUMMARY_INQUIRY');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDT_WRAPUP_SUMMARY_CONVERSATION');

--==========================================================================
--Step 2: Create ASDT_WRAPUP_SUMMARY_CONVERSATION (header, grain: 1 row per conversation)
--==========================================================================

CREATE TABLE ASDT_WRAPUP_SUMMARY_CONVERSATION (
    CONVERSATION_ID VARCHAR(100) NOT NULL,
    MESSAGE_ID VARCHAR(100),
    SEQUENCE_NUMBER NUMBER,
    GENERATED_AT TIMESTAMP_NTZ,
    MODEL_VERSION VARCHAR(100),
    PROMPT_TOKENS NUMBER,
    COMPLETION_TOKENS NUMBER,
    TOTAL_TOKENS NUMBER,
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT ASDT_WRAPUP_SUMMARY_CONVERSATION_PK PRIMARY KEY (CONVERSATION_ID)
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDT_WRAPUP_SUMMARY_CONVERSATION TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDT_WRAPUP_SUMMARY_CONVERSATION TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDT_WRAPUP_SUMMARY_CONVERSATION TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 3: Create ASDT_WRAPUP_SUMMARY_INQUIRY (grain: 1 row per inquiry, FK to CONVERSATION)
--==========================================================================

CREATE TABLE ASDT_WRAPUP_SUMMARY_INQUIRY (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    CONVERSATION_ID VARCHAR(100) NOT NULL,
    INQUIRY_NUMBER VARCHAR(100),
    INQUIRY_ROLE VARCHAR(50),
    INQUIRY_PARENT_NUMBER VARCHAR(100),
    CLASSIFICATION VARCHAR(200),
    DESCRIPTION VARCHAR(4000),
    RESOLUTION VARCHAR(4000),
    STATUS VARCHAR(50),
    INQUIRY_SUMMARY VARCHAR(4000),
    MEME_CK VARCHAR(100),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_PK PRIMARY KEY (INQUIRY_ID),
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_FK1 FOREIGN KEY (CONVERSATION_ID)
        REFERENCES ASDT_WRAPUP_SUMMARY_CONVERSATION (CONVERSATION_ID)
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDT_WRAPUP_SUMMARY_INQUIRY TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDT_WRAPUP_SUMMARY_INQUIRY TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDT_WRAPUP_SUMMARY_INQUIRY TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 4: Create ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT (grain: 1 row per intent, FK to INQUIRY)
--==========================================================================

CREATE TABLE ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    INTENT_ID NUMBER NOT NULL,
    INTENT_LABEL VARCHAR(200),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT_PK PRIMARY KEY (INQUIRY_ID, INTENT_ID),
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT_FK1 FOREIGN KEY (INQUIRY_ID)
        REFERENCES ASDT_WRAPUP_SUMMARY_INQUIRY (INQUIRY_ID)
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDT_WRAPUP_SUMMARY_INQUIRY_INTENT TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 5: Create ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT (grain: 1 row per key point, FK to INQUIRY)
--==========================================================================

CREATE TABLE ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    KEY_POINT_SEQ NUMBER NOT NULL,
    KEY_POINT_TEXT VARCHAR(4000),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_PK PRIMARY KEY (INQUIRY_ID, KEY_POINT_SEQ),
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_FK1 FOREIGN KEY (INQUIRY_ID)
        REFERENCES ASDT_WRAPUP_SUMMARY_INQUIRY (INQUIRY_ID)
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDT_WRAPUP_SUMMARY_INQUIRY_KEY_POINT TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 6: Create ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC (grain: 1 row per topic, FK to INQUIRY)
--==========================================================================

CREATE TABLE ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    TOPIC_SEQ NUMBER NOT NULL,
    TOPIC_TEXT VARCHAR(500),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL,
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC_PK PRIMARY KEY (INQUIRY_ID, TOPIC_SEQ),
    CONSTRAINT ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC_FK1 FOREIGN KEY (INQUIRY_ID)
        REFERENCES ASDT_WRAPUP_SUMMARY_INQUIRY (INQUIRY_ID)
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDT_WRAPUP_SUMMARY_INQUIRY_TOPIC TO ROLE XXX_OWNER COPY CURRENT GRANTS');