/**********************************************************************
** Name            : ASDW_WRAPUP_SUMMARY_WORK_TABLES.sql
**
** Description     : DDL for the 5 wrapup_summary work (staging) tables.
**                   CONVERSATION (header) : INQUIRY (1-to-many) :
**                   INQUIRY_INTENT / INQUIRY_KEY_POINT / INQUIRY_TOPIC
**                   (many-to-one back to INQUIRY via INQUIRY_ID).
**                   Tables are dropped child-to-parent and created
**                   parent-to-child since work tables carry the same
**                   FK relationships as final, just unenforced staging
**                   copies.
**
** Developed By    : BI DW DEV
** Date Created    : 08/16/2026
**
** Change History  :
** Mod            Date         Name           Reason
**----------------------------------------------------------------
** PBI_1830398    08/16/2026   Abhi M         Initial
**
**------------------------------------------------------------------
**********************************************************************/
USE SCHEMA ADMIN;

--==========================================================================
--Step 1: Drop existing work tables (child-to-parent order)
--==========================================================================

CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDW_WRAPUP_SUMMARY_INQUIRY_TOPIC_LOAD');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDW_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_LOAD');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDW_WRAPUP_SUMMARY_INQUIRY_INTENT_LOAD');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDW_WRAPUP_SUMMARY_INQUIRY_LOAD');
CALL TOOLS.ADMIN.SP_DROP_OBJECT('TABLE', 'ADMIN.ASDW_WRAPUP_SUMMARY_CONVERSATION_LOAD');

--==========================================================================
--Step 2: Create ASDW_WRAPUP_SUMMARY_CONVERSATION_LOAD (header, grain: 1 row per conversation)
--==========================================================================

CREATE TABLE ASDW_WRAPUP_SUMMARY_CONVERSATION_LOAD (
    CONVERSATION_ID VARCHAR(100) NOT NULL,
    MESSAGE_ID VARCHAR(100),
    SEQUENCE_NUMBER NUMBER,
    GENERATED_AT TIMESTAMP_NTZ,
    MODEL_VERSION VARCHAR(100),
    PROMPT_TOKENS NUMBER,
    COMPLETION_TOKENS NUMBER,
    TOTAL_TOKENS NUMBER,
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDW_WRAPUP_SUMMARY_CONVERSATION_LOAD TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDW_WRAPUP_SUMMARY_CONVERSATION_LOAD TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDW_WRAPUP_SUMMARY_CONVERSATION_LOAD TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 3: Create ASDW_WRAPUP_SUMMARY_INQUIRY_LOAD (grain: 1 row per inquiry)
--==========================================================================

CREATE TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_LOAD (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    CONVERSATION_ID VARCHAR(100) NOT NULL,
    INQUIRY_NUMBER VARCHAR(100),
    INQUIRY_ROLE VARCHAR(50),
    INQUIRY_PARENT_NUMBER VARCHAR(100),
    CLASSIFICATION VARCHAR(200),
    DESCRIPTION VARCHAR(4000),
    RESOLUTION VARCHAR(4000),
    STATUS VARCHAR(50),
    INQUIRY_SUMMARY VARCHAR(4000),
    MEME_CK VARCHAR(100),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDW_WRAPUP_SUMMARY_INQUIRY_LOAD TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDW_WRAPUP_SUMMARY_INQUIRY_LOAD TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_LOAD TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 4: Create ASDW_WRAPUP_SUMMARY_INQUIRY_INTENT_LOAD (grain: 1 row per intent)
--==========================================================================

CREATE TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_INTENT_LOAD (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    INTENT_ID NUMBER,
    INTENT_LABEL VARCHAR(200),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDW_WRAPUP_SUMMARY_INQUIRY_INTENT_LOAD TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDW_WRAPUP_SUMMARY_INQUIRY_INTENT_LOAD TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_INTENT_LOAD TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 5: Create ASDW_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_LOAD (grain: 1 row per key point)
--==========================================================================

CREATE TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_LOAD (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    KEY_POINT_SEQ NUMBER NOT NULL,
    KEY_POINT_TEXT VARCHAR(4000),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDW_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_LOAD TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDW_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_LOAD TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_KEY_POINT_LOAD TO ROLE XXX_OWNER COPY CURRENT GRANTS');

--==========================================================================
--Step 6: Create ASDW_WRAPUP_SUMMARY_INQUIRY_TOPIC_LOAD (grain: 1 row per topic)
--==========================================================================

CREATE TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_TOPIC_LOAD (
    INQUIRY_ID VARCHAR(32) NOT NULL,
    TOPIC_SEQ NUMBER NOT NULL,
    TOPIC_TEXT VARCHAR(500),
    UPDATED_ON TIMESTAMP_NTZ NOT NULL,
    LOAD_TS TIMESTAMP_NTZ NOT NULL
);

CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, SELECT ON ASDW_WRAPUP_SUMMARY_INQUIRY_TOPIC_LOAD TO ROLE XXX_RESTRICTED_TABLEREADER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT REFERENCES, INSERT, UPDATE, DELETE, TRUNCATE ON ASDW_WRAPUP_SUMMARY_INQUIRY_TOPIC_LOAD TO ROLE XXX_TABLEWRITER');
CALL TOOLS.ADMIN.SP_APPLY_GRANT('GRANT OWNERSHIP ON TABLE ASDW_WRAPUP_SUMMARY_INQUIRY_TOPIC_LOAD TO ROLE XXX_OWNER COPY CURRENT GRANTS');