/**********************************************************************
** Name            : PBI_XXXXXXX_Populate_ABIT_CARE_PROGRAM_DETAILS_REPORT.sql
**
** Description     : Refresh table ABIT_CARE_PROGRAM_DETAILS_REPORT
**
** Developed By    : BI DW DEV
** Date Created    : 08/17/2026
**
** Change History  :
** Mod            Date         Name           Reason
**----------------------------------------------------------------
** PBI_XXXXXXX    08/17/2026   Abhi M         Initial
**
**------------------------------------------------------------------
**********************************************************************/

--Truncate table
TRUNCATE TABLE ABIT_CARE_PROGRAM_DETAILS_REPORT;

--Populate table
INSERT INTO ABIT_CARE_PROGRAM_DETAILS_REPORT
SELECT
CLIENT
, LOB
, PLAN_TYPE
, OPS_SEGMENT
, TPA_NAME
, PATIENT
, DATE_OF_BIRTH
, PATIENT_ID
, PROGRAM
, PROGRAM_ID
, PCP_CARE_COORDINATION_NAME
, PCP_CARE_COORDINATION_NPI
, PCP_INSURANCE_NAME
, PCP_INSURANCE_NPI
, PRACTICE_NAME
, IFF(PROVIDER_OUTREACH_REQUESTED = FALSE, 'No', PROVIDER_OUTREACH_REQUESTED::VARCHAR) AS PROVIDER_OUTREACH_REQUESTED
, PROGRAM_STATUS
, PROGRAM_PRIORITY
, REFERRAL_SOURCE
, DELIVERY_MODEL
, REASON_FOR_PROGRAM
, PRIMARY_STAFF_MEMBER
, PRIMARY_STAFF_ROLE
, OTHER_CARE_TEAM_MEMBER
, OTHER_CARE_TEAM_MEMBER_ROLE
, TO_TIMESTAMP_NTZ(DATE_PRIMARY_STAFF_ASSIGNED, 'MM/DD/YYYY HH12:MI:SS AM') AS DATE_PRIMARY_STAFF_ASSIGNED
, FACILITY_NAME
, FACILITY_TYPE
, TO_TIMESTAMP_NTZ(ADMIT_DATE, 'MM/DD/YYYY') AS ADMIT_DATE
, TO_TIMESTAMP_NTZ(TARGET_DISCHARGE_DATE, 'MM/DD/YYYY') AS TARGET_DISCHARGE_DATE
, TO_TIMESTAMP_NTZ(ACTUAL_DISCHARGE_DATE, 'MM/DD/YYYY') AS ACTUAL_DISCHARGE_DATE
, DISCHARGE_DISPOSITION
, DISCHARGE_DELAY_REASON
, PROGRAM_CREATE_DATE
, PROGRAM_CREATED_BY
, TO_TIMESTAMP_NTZ(PROGRAM_ASSIGNED_DATE, 'MM/DD/YYYY') AS PROGRAM_ASSIGNED_DATE
, PROGRAM_START_DATE
, TO_TIMESTAMP_NTZ(PROGRAM_CLOSED_DATE, 'YYYY-MM-DD') AS PROGRAM_CLOSED_DATE
, TO_TIMESTAMP_NTZ(LAST_PROGRAM_ACTIVITY_DATE, 'MM/DD/YYYY HH12:MI:SS AM') AS LAST_PROGRAM_ACTIVITY_DATE
, LAST_PROGRAM_ACTIVITY_BY
, TOTAL_SUBMITTED_ASSESSMENTS
, TOTAL_DRAFT_ASSESSMENTS
, TO_TIMESTAMP_NTZ(FIRST_ASSESSMENT_SUBMITTED_DATE_ENGAGEMENT_DATE, 'MM/DD/YYYY HH12:MI:SS AM') AS FIRST_ASSESSMENT_SUBMITTED_DATE_ENGAGEMENT_DATE
, TO_TIMESTAMP_NTZ(LAST_ASSESSMENT_SUBMITTED_DATE, 'MM/DD/YYYY HH12:MI:SS AM') AS LAST_ASSESSMENT_SUBMITTED_DATE
, NAME_OF_LAST_SUBMITTED_ASSESSMENT
, TO_TIMESTAMP_NTZ(ENGAGED_DATE, 'MM/DD/YYYY HH12:MI:SS AM') AS ENGAGED_DATE
, TOTAL_PATIENT_CONTACTS
, TO_TIMESTAMP_NTZ(FIRST_PATIENT_CONTACT_DATE, 'MM/DD/YYYY HH12:MI:SS AM') AS FIRST_PATIENT_CONTACT_DATE
, TO_TIMESTAMP_NTZ(LAST_PATIENT_CONTACT_DATE, 'MM/DD/YYYY HH12:MI:SS AM') AS LAST_PATIENT_CONTACT_DATE
, TOTAL_UNSIGNED_CARE_NOTES
, TOTAL_OPEN_ACTION_ITEMS
, TOTAL_OVERDUE_ACTION_ITEMS
, TOTAL_SUCCESSFULLY_CLOSED_PROGRAM_GRADUATION_GOALS
, TOTAL_OVERDUE_GOALS
, TOTAL_OVERDUE_INTERVENTIONS
, TO_TIMESTAMP_NTZ(FIRST_CARE_PLAN_DATE, 'MM/DD/YYYY HH12:MI:SS AM') AS FIRST_CARE_PLAN_DATE
, NUMBER_OF_CARE_PLANS
, LAST_PCSP_COMPLETED
, TOTAL_PCSPS_COMPLETED
, TO_TIMESTAMP_NTZ(LAST_CMR_SUBMITTED_DATE, 'MM/DD/YYYY') AS LAST_CMR_SUBMITTED_DATE
, TO_TIMESTAMP_NTZ(WELCOME_PACKET_GENERATED_DATE, 'MM/DD/YYYY') AS WELCOME_PACKET_GENERATED_DATE
, TOTAL_LETTERS_GENERATED
, TOTAL_UPLOADED_DOCUMENTS
, CURRENT_TIMESTAMP() AS LOAD_TS
FROM BI_Workspace.admin.abit_CARE_PROGRAM_DETAILS_REPORT_backup_081726;